/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv1simkoAmbulanceWlList {
    }
}
declare global {
    interface HTMLCv1simkoAmbulanceWlListElement extends Components.Cv1simkoAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv1simkoAmbulanceWlListElement: {
        prototype: HTMLCv1simkoAmbulanceWlListElement;
        new (): HTMLCv1simkoAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv1simko-ambulance-wl-list": HTMLCv1simkoAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv1simkoAmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv1simko-ambulance-wl-list": Cv1simkoAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv1simko-ambulance-wl-list": LocalJSX.Cv1simkoAmbulanceWlList & JSXBase.HTMLAttributes<HTMLCv1simkoAmbulanceWlListElement>;
        }
    }
}
